### ISSUE TITLE
How to extract token

### ISSUE THREAD

**Issue by kambleaa007** [snj07/spring-oauth-jpa-demo#1]
Backend spring boot, spring security `websecurityadapter`,
Front end Angular or ReactJS
I Was implementing OAuth2 Google, FB SSO,
It does store actually JSESSION Cookie,
and then let app tell that user is now authenticated,
I dont want this default feature i want tokens in header like you,
I serached alot i didnt find way to stop that cookie and turn it into token, 
Which part of code would convert it into JWT 
and 
make it `Header Authentication : Bearer token`, does filters do that or any framework do it

**Comment by snj07** [comment]
You can store the token in local storage and send it as part of cookies in the future requests.

**Comment by kambleaa007** [comment]
Yes, I can do that, when using OAuth2 alot redirection happens,
my app-> google OAuth server->after login suceessfully -> it just sets browser cookie with JSESSIONID name,
Is it safe to have cookie (thats default by spring security sso)
Is that the same way Real Time Project works ?

**Comment by snj07** [comment]
You can send encrypted token and store it in cookies or you can use other ways to store the token securely in angular. You can easily find it on Google.
